language: java

sudo: required
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
before_install:
 - chmod +x gradlew

script:
 - ./gradlew assemble
 - ./gradlew check
 - ./gradlew clean build
install:
- true
