
language: java

sudo: required
jdk:
  - oraclejdk8
cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - $HOME/.gradle/
  
before_install:
 - chmod +x gradlew

script:
 - ./gradlew assemble
 - ./gradlew check
 - ./gradlew clean build
 - ./gradlew install
install:
- true