language: java

sudo: required
jdk:
  - oraclejdk8

before_install:
 - chmod +x gradlew

script:
 - ./gradlew assemble
 - ./gradlew check
 - ./gradlew clean build
install:
- true

script:
- gradle uploadModToMaven -Dorg.ajoberstar.grgit.auth.username=$GITHUB_REPO_AUTH_USERNAME -Dorg.ajoberstar.grgit.auth.password=$GITHUB_REPO_AUTH_PASSWORD